// This file is auto-generated by AWS Amplify
// Do not modify this file - it will be overwritten by Amplify CLI
// This is just a placeholder - the actual file will be generated when you run 'amplify push'